### ISSUE TITLE
Is there a method to close the connection?

### ISSUE THREAD

**Issue by eduardrock** [tryggingamidstodin/node-jt400#41]
I need to close the DB connection once the data is retrieved or when it throws an error.
Is there something like `db.close()`?

**Comment by cwg999** [comment]
`pool.close()` perhaps?

**Comment by eduardrock** [comment]
great, it worked!.
Why that method is not on the documentation?

**Comment by cwg999** [comment]
Small package, not too many people who use this, company who created it (tryggingamidstodin) released it for free. I can read the code and understand the node-jt400 / jt400 java documentation so there's no need for me or likely the other users/authors to add it. You're very welcome to create a PR to edit the README with the note, as the maintainers do often accept and merge in PRs.

**Comment by bergur** [comment]
Hi @eduardrock 

Cody is right on the money as usual. This was originally created for internal use but we thought maybe other people might need similar solution since IBM AS400 is a legacy system in many companies.

We welcome most contributions and are always trying to improve the documentation.  I think maybe one problem is that we aren't clear enough that this is module is just mapping the [IBM Toolbox for Java](http://jt400.sourceforge.net/) from Java to Node. So when you have a connection pool its the same as the Java one. 

I will add that note and your comment about the close function to the documentation.
