### ISSUE TITLE
Is there a way to read DTAQ or OUTQ files

### ISSUE THREAD

**Issue by dot3x3** [tryggingamidstodin/node-jt400#50]
Hi,
i've seen you can read messagequeues. Is it possible to read or even list printerqueues/dataqueues  as well?

**Comment by cwg999** [comment]
If you can do it in jt400 you can do it in node-jt400, unfortunately I only implemented keyed data queues because it was what I needed. I don't think we have data queue support, but it might be trivial for you to copy what I did for keyed data queues and extend it to data queues. The reason the code base is like this is because tryggingamidstodin is an icelandic company that only implemented what they needed from jt400 as well, but they're very open to pull requests.

**Comment by bergur** [comment]
Hi @dot3x3, my name is Bergur. I am developer at Tryggingamidstodin. 

As usual, Cody is right on money: Yes it possible but not yet implement. If you check out: [https://developer.ibm.com/articles/i-javatoolbox/](https://developer.ibm.com/articles/i-javatoolbox/) it states:

> Print resources can be accessed using the print classes: OutputQueue, Printer, PrinterFile, SpooledFile, and WriterJob.

Check out the API here: [https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_71/rzahh/javadoc/com/ibm/as400/access/PrintObject.html](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_71/rzahh/javadoc/com/ibm/as400/access/PrintObject.html)

My reccomendation would be to implement this feature first in Java and get that fully functioning. When that is running as expected you should be able to wire it together in node-jt400 in the same way @cwg999 did with keyed data queues.

Let me know if there's anything else I can help you with.

**Comment by dot3x3** [comment]
Thanks guys, i'll take a look into that.
