### ISSUE TITLE
KeyedDataQ Not available

### ISSUE THREAD

**Issue by PolluxFR76** [tryggingamidstodin/node-jt400#59]
I got the following issue when I try to invoke KeyedDataQ :

const dq = connection.createKeyedDataQ(opt.name);
                                  ^

Error: Error running instance method
com.ibm.as400.access.ExtendedIllegalArgumentException: objectName (LAMFIC_V4/VLDQSE03): Length is not valid.
        at com.ibm.as400.access.QSYSObjectPathName.checkObjectName(QSYSObjectPathName.java:465)
        at com.ibm.as400.access.QSYSObjectPathName.toPath(QSYSObjectPathName.java:1098)
        at nodejt400.KeyedDataQ.<init>(KeyedDataQ.java:21)
        at nodejt400.JT400.createKeyedDataQ(JT400.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

    at Object.createKeyedDataQ (C:\DEV\node_modules\←[4mnode-jt400←[24m\dist\lib\jt400.js:265:35)
    at Object.<anonymous> (C:\DEV\JT400\evalidation.js:12:19)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1102:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:967:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:807:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m {
  cause: nodeJava_com_ibm_as400_access_ExtendedIllegalArgumentException {}
}

I use the example provided with a name for the LIB/KeyedDtaQ such as  : 
const jt400 = require('node-jt400').pool(config);
var name = 'QSYS.LIB/MYDTAQ';
// const jt400 = pool(config);
// Open a keyed data queue for reading
let queue = jt400.createKeyedDataQ({name}); 
// -1 waits until a message exists. (MSGW)
let m =  queue.read({key:inboxKey,wait:-1});

**Comment by cwg999** [comment]
Hi PolluxFR76, I would try `t400.createKeyedDataQ({name:opt.name});`

**Comment by bergur** [comment]
Hi @PolluxFR76 the problem is that the name options only wants the name, not the library

Check out how the tests for createKeyedDataQ are:
https://github.com/tryggingamidstodin/node-jt400/blob/master/test/dataq-spec.ts#L6

`const dataQ = jt400.createKeyedDataQ({ name: 'SDQS1' })`

In the java code you can see how the program creates the path.
https://github.com/tryggingamidstodin/node-jt400/blob/master/java/src/nodejt400/KeyedDataQ.java#L21

`this.path = QSYSObjectPathName.toPath("*LIBL", name, "DTAQ");`

toPath takes in libraryName, objectName and objectType
https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/rzahh/javadoc/com/ibm/as400/access/QSYSObjectPathName.html#toPath(java.lang.String,%20java.lang.String,%20java.lang.String)

In the node-jt400 code the libraryName and the objectType is already declared, so you just need to pass the objectName

**Comment by PolluxFR76** [comment]
Effectively, I forgot to mention the library name in the config. 

Thanks
