### ISSUE TITLE
How to execute stored proc with INOUT parameters?

### ISSUE THREAD

**Issue by HenryJW** [tryggingamidstodin/node-jt400#9]
I've tried using the `.execute()` method as below, but I get a null pointer exception from Java; presumably because the stored proc doesn't return a results and the Java code expects it to. Is it possible with this library? I was also looking at the `.pgm()` method, but was unable to execute it due to lack of documentation (how to specify param type?).
Any help is greatly appreciated!

```javascript
const pool = require('node-jt400')({/*connection settings*/})

/*some code*/

// not the actual query, but gets the point across
const storedProcQuery =  `
    BEGIN
        DECLARE OUT_PARAM VARCHAR(3)
        CALL MY_STORED_PROC(OUT_PARAM);
    END`;

pool.execute(storedProcQuery)
    .then(statement => statement.asArray())
    .then(result => {
        console.log(result)
    })
    .catch(err => {
        console.error(err)
    })
```

```
Error running instance method
java.lang.NullPointerException
	at nodejt400.StatementWrap.asArray(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by bergur** [comment]
Hi @HenryJW and sorry for the late reply. My name is Bergur and I work for @tryggingamidstodin.

The node-jt400 module does not support stored procedures. The execute method expects pure sql.

Regarding the pgm method it accepts to parameters
1) Program name
2) Program schema

```javascript
const myprogram = pool.pgm('MYPROGRAM', [
            { type: 'DECIMAL', precision: 10, scale: 0, name: 'myId'},
            { type: 'NUMERIC', precision: 8, scale: 0, name: 'myYYYYMMDD'}
            { type: 'NUMERIC', precision: 12, scale: 2, name: 'myTotalValue' },
            { type: 'CHAR', precision: 32, scale: 0, name: 'myString'}
]);
```

The Decimal type maps to com.ibm.as400.access.AS400PackedDecimal 
The Numeric type maps to com.ibm.as400.access.AS400ZonedDecimal
Everything else (char) maps to com.ibm.as400.access.AS400Text

Precision is the size and scale is the decimals. Hope this helps.

**Comment by HenryJW** [comment]
Thanks for your reply @bergur.  Since executing stored procs is currently not supported by this library, do you know if jt400 itself supports it? I'm not too familiar with jt400 but I'm curious to know if an implementation is even possible.

Thanks

**Comment by bergur** [comment]
Yeah AS400 has stored procedures, so it would be possible to implement it.

**Comment by HenryJW** [comment]
Ah. I was under the impression that jt400 was another Java library, but after skimming through the Java code it seems that it's actually the interface to the database.

Thanks for your help!

**Comment by bergur** [comment]
Yeah JT400 (aka IBM Toolbox for Java) is a Java library to connect to a AS400 server (that has a OS400 operating system and a database like DB2 for example). It uses a JDBC Driver.

This library (node-jt400) uses:
1) Java code to connect to AS400, using JT400, that is then built/compiled.
2) Node code that utilizes a node Java module (https://www.npmjs.com/package/java) to map/bridge between.

So basically we're mapping the java functions to node functions. Since AS400 and the JT400 library supports stored procedures it would be possible to write the java code for it and then let the nodejs code call that function.

The only reason that we haven't implemented it is because @tryggingamidstodin hasn't had any needs for it so far

**Comment by HenryJW** [comment]
Ah, understand now. Thanks a lot for the clarification.

**Comment by natewaite** [comment]
Are you planning on stored procedures?

**Comment by bergur** [comment]
Hi @natewaite 

No, not at the moment. Tryggingamidstodin is an Icelandic insurance company and this module was written in order to move some of our old logic from AS400/RPG to our new nodeJS solutions.

Features that are currently in the module are features that we needed. We have never used stored procedures so there was never a need for the software department to map that between the Java toolbox and the node code.

We are open to pull-requests if they are relevant and well tested :)

**Comment by OlafurTorfi** [comment]
Hi @henryjw, @natewaite and @bergur 

Perhaps this is not directly addressing the problem, but maybe it helps.

You can create stored functions like:
CREATE FUNCTION myfunction
  (foo INTEGER)   
  RETURNS INTEGER
  Language SQL
    BEGIN
      DECLARE bar INTEGER DEFAULT 34;
      RETURN foo + bar;
    END

and call them like:
await db.query("select myfunction(?)) foobar from sysibm.sysdummy1",[1200])
